repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict

  # Python Backend hooks
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        files: ^backend/
        language_version: python3.11

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        files: ^backend/
        args: [--fix, --exit-non-zero-on-fix]

  - repo: local
    hooks:
      - id: backend-tests
        name: Backend Tests
        entry: bash -c 'cd backend && pytest'
        language: system
        files: ^backend/
        pass_filenames: false

  # Python AI Service hooks
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        files: ^ai-service/
        language_version: python3.11

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        files: ^ai-service/
        args: [--fix, --exit-non-zero-on-fix]

  - repo: local
    hooks:
      - id: ai-service-tests
        name: AI Service Tests
        entry: bash -c 'cd ai-service && pytest'
        language: system
        files: ^ai-service/
        pass_filenames: false

  # Frontend hooks
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^frontend/
        additional_dependencies:
          - prettier@3.1.0
        exclude: ^frontend/coverage/

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.54.0
    hooks:
      - id: eslint
        files: ^frontend/.*\.(js|jsx|ts|tsx)$
        additional_dependencies:
          - eslint@8.54.0
          - eslint-config-next@14.0.0
        args: [--fix]

  - repo: local
    hooks:
      - id: frontend-tests
        name: Frontend Tests
        entry: bash -c 'cd frontend && npm test -- --passWithNoTests --watchAll=false'
        language: system
        files: ^frontend/
        pass_filenames: false