version: '3.8'

# Development overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  backend:
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
    volumes:
      - ./backend:/app
    command: flask run --host=0.0.0.0 --reload

  ai-service:
    environment:
      RELOAD: "true"
    volumes:
      - ./ai-service:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev