name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
    types: [ opened, synchronize, reopened ]

env:
  NODE_VERSION: '20'
  PYTHON_VERSION: '3.11'

# Ensure CI fails if any job fails
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Frontend Tests
  frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Lint check
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build

  # Backend Tests
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: './backend/requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check formatting
        run: black --check .

      - name: Lint check
        run: ruff check .

      - name: Run tests
        run: pytest

  # AI Service Tests
  ai-service:
    name: AI Service Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ai-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: './ai-service/requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check formatting
        run: black --check .

      - name: Lint check
        run: ruff check .

      - name: Run tests
        run: pytest

  # Docker Build Tests
  docker-build:
    name: Docker Build Tests
    runs-on: ubuntu-latest
    needs: [frontend, backend, ai-service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Test Docker Compose
        run: |
          docker-compose -f docker-compose.yml config
          echo "Docker Compose configuration is valid"

  # Jira Integration
  jira-integration:
    name: Jira Integration
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Extract Jira ticket from PR title
        id: extract
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          TICKET=$(echo "$TITLE" | grep -oE 'SPRNT2-[0-9]+' || echo "")
          echo "ticket=$TICKET" >> $GITHUB_OUTPUT

      - name: Validate Jira ticket reference
        if: steps.extract.outputs.ticket == ''
        run: |
          echo "❌ PR title must include Jira ticket reference (SPRNT2-XX)"
          echo "Current title: ${{ github.event.pull_request.title }}"
          exit 1

      - name: Validate conventional commit format
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          if ! echo "$TITLE" | grep -qE '^(feat|fix|docs|style|refactor|test|chore)\(SPRNT2-[0-9]+\):'; then
            echo "❌ PR title must follow conventional commit format"
            echo "Format: type(SPRNT2-XX): description"
            echo "Example: feat(SPRNT2-14): add chat interface"
            echo "Current title: $TITLE"
            exit 1
          fi
          echo "✅ PR title follows conventional commit format"